<?php
	if ($this->agent->is_mobile()) {
		$width = 275;
		$height = 194;
	} else {
		$width = 425;
		$height = 300;		
	}
?>
<h3>Vehicle Location - May 2011</h3>
<center><object width="<?php echo $width; ?>" height="<?php echo $height; ?>"><param name="movie" value="http://www.youtube.com/v/8LEwFlnk74w?hl=en&fs=1"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/8LEwFlnk74w?hl=en&fs=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="<?php echo $width; ?>" height="<?php echo $height; ?>"></embed></object></center>
<h4 class = "click"><a href = "<?php echo BASE_URL; ?>public/pdfs/E90_Final.pdf" target="_blank">Full PDF Version</a></h4>
<p class = "blog">For my senior design project, I created a system to determine a vehicles location along a known route and derived additional information such as estimated time of arrival which is displayed on a website with the use of Google Maps for the student body. This system uses GPS to measure the position of the vehicle. A Kalman Filter is then used to integrate the noisy unreliable GPS measurements along with the predefined route to find a combined position estimate. A centralized server then runs the Kalman Filter and presents data in real-time to users through a web interface. While this Advance Vehicle Locator (AVL) applications can only be simulated with previously collected GPS data, it could be easily modified so it can be implemented for several student run shuttles at Swarthmore College.</p>
<h3>Quality of Coronary Artery Bypass Graft Surgery Overtime - December 2010</h3>
<h4 class = "click"><a href = "<?php echo BASE_URL; ?>public/pdfs/CABG Paper.pdf" target="_blank">Full PDF Version</a></h4>
<p class = "blog">Since 1989, New York State has published the coronary artery bypass graft sugery (CABG) Report Card to record the number of CABG surgeries a doctor has done in addition to mortality rates to improve patient care. There is a common notion that with age comes experience and improved patient care, however when does the age of a doctor become a physical burden to patient care. I have found data that suggests that age will become a burden over the age of 53. While this data is by no means conclusive it suggests that the medical profession needs to take a deeper look into how age affects a doctor.s quality.</p>
<h3>Space-Based Position Navigation and Timing Systems - July 2010</h3>
<h4 class = "click"><a href = "<?php echo BASE_URL; ?>public/pdfs/Final_Multi-GNSS.pdf" target="_blank">Full PDF Version</a></h4>
<p class = "click">Alan Lakein once said, 'Planning is bringing the future into the present so that you can do something about it now'.  While The United States has the only fully operational Global Navigation Satellite System (GNSS), known as the Global Positioning System (GPS), several other countries are in the process of developing their own systems. There are also several Regional Navigation Satellite Systems (RNSS), and Satellite-based Augmentation Systems (SBAS) being implemented or are already operational. With the implementation of these space-based position, navigation and timing (PNT) systems we can significantly improve the world.s safety and well being, in an economically efficient manner. For these space-based PNT systems to improve our quality of life they must promote compatibility, interoperability, openness and integrity for all users. We must now plan for these additional systems implementations to improve not just our Nation.s well being, but the world.s.</p>
<h3>Color and Economics Choice - March 2010</h3>
<h4 class = "click"><a href="<?php echo BASE_URL; ?>public/pdfs/color_experiment.pdf" target="_blank">Full PDF Version</a></h4>
<p class = "blog">Does color, specifically red and green, affect a person's certainty equivalent in a price list format? To test this question, I created a series of price list questions where people to choose their preferences, but had the background be in either red or green. People who were given the price list questions with a red background had a higher certainty equivalent than if they were given the questions in green. This suggests that people, who were given the red questions, subconsciously viewed the price list in a more risk averse manner and therefore tended to have a higher certainty equivalent than people who were given the questions in green, who tended to be more risk seeking.</p>
